#
# Build configuration for Circle CI
#
general:
    artifacts:
        - /home/ubuntu/unideal-android/app/build/outputs/apk/
machine:
    environment:
        ANDROID_HOME: /usr/local/android-sdk-linux
dependencies:
    override:
        # Build Tools 25.0.1
        - echo y | android update sdk --no-ui --all --filter build-tools-25.0.2,android-25,extra-android-m2repository
        # Build Tools 24.0.1
#        - echo y | android update sdk --no-ui --all --filter build-tools-24.0.3,android-24,extra-android-m2repository
#        # Build Tools 23.0.1
#        - echo y | android update sdk --no-ui --all --filter build-tools-23.0.2,android-23,extra-android-m2repository
        - ANDROID_HOME=/usr/local/android-sdk-linux ./gradlew dependencies
test:
  override:
  # start the build
  - ./gradlew assembleDebug
 # copy the build outputs to artifacts
  - cp -r app/build/outputs/ $CIRCLE_ARTIFACTS